package net.andreu.SeriesTV;

import javafx.fxml.FXML;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class SeriesTVController {
	@FXML
	private TextField nomSeria;
	@FXML
	private Button buscar;
	@FXML
	private ListView<String> llistaCapitols;
	@FXML
	private Label capCas;
	@FXML
	private Label capSub;
	@FXML
	private Label capAng;
	@FXML
	private ImageView imgSeria;
	@FXML
	private ComboBox<String> llistaTemporades;

	// Event Listener on Button[#buscar].onMouseClicked
	@FXML
	public void buscarSeria(MouseEvent event) {

		String nom=nomSeria.getText();
		llistaTemporades.getItems().clear();
		
		WebDriver navegador = new FirefoxDriver();
        navegador.navigate().to("http://seriesblanco.com");
        
        WebElement buscar = navegador.findElement(By.id("buscar-blanco"));
        buscar.sendKeys(nom);
        buscar.submit();
        
        WebElement seria = navegador.findElement(By.className("ict"));
        seria.click();
        
		/*WebElement img = navegador.findElement(By.id("port_serie"));
        //String imatge = img.getAttribute("src");
		Image imatge = new Image(img.getAttribute("src"));
        imgSeria.setImage(imatge);*/
        
		for(WebElement t : navegador.findElements(By.xpath("//h2/u"))){
			llistaTemporades.getItems().add(t.getText());
		}
	}
	
	// Event Listener on ComboBox[#llistaTemporades].onAction
	@FXML
	public void triarTemporada(ActionEvent event) {
		// TODO Autogenerated
	}
}
